A2/pics/config/routes.rb
Pics::Application.routes.draw do

  root :to => 'home#index'

  match 'auth/:provider/callback', to: 'sessions#create_omniauth'
  match 'auth/failure', to: 'home#index'
  match 'signout', to: 'sessions#destroy', as: 'signout'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :users, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :sessions
  resources :photos
  resources :tags
  resources :play, only: [:index, :create]
  resources :scores, only: [:index, :show]

end

A2/pics/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation, :role

  attr_accessor :password

  has_one :game
  has_many :scores
  
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_presence_of :name

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = user.uid + auth.provider
      user.password = "Random"
      user.password_confirmation = "Random"
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

A2/pics/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :find_user, :only => [:show, :edit, :update]

  def find_user
    @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      render_404
  end

  def render_404
    respond_to do |format|
      format.html { render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found }
      format.xml  { head :not_found }
      format.any  { head :not_found }
    end
  end

  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash.now.alert = "Successfully updated!"
      render :action => 'edit', :id => @user.id
    else
      flash.now.alert = "Try again!"
      render :action => 'edit', :notice => "Try again!"
    end
  end

  def destroy
    User.find(params[:id]).destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Deleted!"
  end
end

A2/pics/app/helpers/users_helper.rb
module UsersHelper
end

A2/pics/app/views/users/edit.html.erb
<h1>Edit Details</h1>

<% if @current_user %>
  <% if @current_user.admin %>
    <%= link_to "View other users", users_path %><br /><br />
  <% end %>
<% end %>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name, :value => @user.name %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= @user.email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>
<%= button_to "Delete Profile", user_path(@user.id), :method => :delete, data: {confirm: "You sure?"} %>

A2/pics/app/views/users/index.html.erb
<h1>Users</h1>

<%= link_to "Add a new user", sign_up_path %><br /><br />

<% if @users %>
  <table>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Admin</th>
    </tr>
  <% @users.each do |user| %>
    <tr>
    <td><%= link_to user.name, edit_user_path(user.id) %></td>
    <td><%= user.email %></td>
    <td><%= user.admin %></td>
    </tr>
  <% end %>
  </table>
<% end %>

A2/pics/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

A2/pics/app/views/users/show.html.erb
<h1>Your details!</h1>

<div id="user_details">
  <% if @user %>
    Name : <%= @user.name %><br />
    Email : <%= @user.email %><br />
    Admin : <%= @user.admin %>
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
</div>