A2/pics/config/routes.rb
Pics::Application.routes.draw do

  root :to => 'home#index'

  match 'auth/:provider/callback', to: 'sessions#create_omniauth'
  match 'auth/failure', to: 'home#index'
  match 'signout', to: 'sessions#destroy', as: 'signout'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :users, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :sessions
  resources :photos
  resources :tags
  resources :play, only: [:index, :create]
  resources :scores, only: [:index, :show]

end

A2/pics/app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name

  has_and_belongs_to_many :photos

  validates_presence_of :name
  validates_uniqueness_of :name
end

A2/pics/app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all 
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.create(params[:tag])
    if @tag.save
      redirect_to tags_path
    else
      render "new"
    end
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def edit
    @tag = Tag.find(params[:id])
  end
  
  def destroy
    Tag.find(params[:id]).destroy
    redirect_to tags_path
  end
end

A2/pics/app/helpers/tags_helper.rb
module TagsHelper
end

A2/pics/app/views/tags/edit.html.erb
<h1>Tags#edit</h1>

<%= link_to "View other tags", tags_path %><br /><br />

<%= form_for @tag do |form| %>
  <%= form.text_field :name %>
  <p class="button"><%= form.submit %></p>
  <%= link_to "Delete Tag", tag_path(@tag.id), 
    :method => :delete %>
<% end %>

A2/pics/app/views/tags/index.html.erb
<h1>Tags#index</h1>

<%= link_to "Create a new tag", new_tag_path %><br />

<% if @tags %>
  <ul>
  <% @tags.each do |tag| %>
    <li><%= link_to tag.name, edit_tag_path(tag.id) %></li>
  <% end %>
  </ul>
<% else %>
  <h3>No tag found!</h3>
<% end %>

A2/pics/app/views/tags/new.html.erb
<h1>Tags#new</h1>

<%= link_to "View other tags", tags_path %><br /><br />

<%= form_for @tag do |form| %>
  <%= form.text_field :name %>
  <p class="button"><%= form.submit %></p>
<% end %>

A2/pics/app/views/tags/show.html.erb
<h1>Tags#show</h1>

<%= link_to "View other tags", tags_path %><b2 />

<h2><%= @tag.name %><br /><br /></h2>