A2/pics/config/routes.rb
Pics::Application.routes.draw do

  root :to => 'home#index'

  match 'auth/:provider/callback', to: 'sessions#create_omniauth'
  match 'auth/failure', to: 'home#index'
  match 'signout', to: 'sessions#destroy', as: 'signout'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :users, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :sessions
  resources :photos
  resources :tags
  resources :play, only: [:index, :create]
  resources :scores, only: [:index, :show]

end

A2/pics/app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :image,:tag_ids

  has_and_belongs_to_many :tags

  has_attached_file :image, styles: { small: "100x100", med: "200x200", large: "400x400" },
                  :url  => "/assets/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/:id/:style/:basename.:extension"

  validates_attachment_presence :image
  validates_attachment_size :image, :less_than => 5.megabytes
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']
end

A2/pics/app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @photos = Photo.all 
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.create(params[:photo])
    if @photo.save
      render :action => 'show', :id => @photo.id
    else
      render "new"
    end
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    params[:photo][:tag_ids] ||= []
    @photo = Photo.find(params[:id])
    if @photo.update_attributes(params[:photo])
      flash.now.alert = "Successfully updated!"
      render :action => 'edit', :id => @photo.id
    else
      flash.now.alert = "Try again!"
      render :action => 'edit', :notice => "Try again!"
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def destroy
    Photo.find(params[:id]).destroy
    redirect_to photos_path, :notice => "Deleted"
  end
end

A2/pics/app/views/photos/edit.html.erb
<h1>Edit</h1>

<%= link_to "View other photos", photos_path %><br />  
<%= link_to "Create a new tag", new_tag_path %><br />

<%= form_for @photo, :url => photo_path, :html => { :multipart => true } do |form| %>
  <%= image_tag @photo.image.url(:med) %>
  <h3>Tags</h3>
  <% for tag in Tag.find(:all) %>
    <div>
      <%= check_box_tag "photo[tag_ids][]", tag.id, @photo.tags.include?(tag) %>
      <%= tag.name %>
    </div>
  <% end %>
  <p class="button"><%= form.submit %></p>
<% end %>
<%= button_to "Delete", photo_path(@photo.id), :method => :delete, 
    data: {confirm: "You sure?"} %>

A2/pics/app/views/photos/index.html.erb
<h1>All Photos</h1>

<%= link_to "Add new photo", new_photo_path %><br />

<% if @photos %>
  <% @photos.each do |photo| %>
    <%= link_to image_tag(photo.image.url(:med)), edit_photo_path(photo.id) %>
  <% end %>
<% else %>
  <h3>No photos found!</h3>
<% end %>

A2/pics/app/views/photos/new.html.erb
<h1>Image#new</h1>




<%= form_for @photo, :url => photos_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :image %>
  <p class="button"><%= form.submit %></p>
<% end %>

A2/pics/app/views/photos/show.html.erb
<h1>Play#show</h1>


<%= link_to image_tag(@photo.image.url(:med)), edit_photo_path(@photo.id) %>