A2/pics/config/routes.rb
Pics::Application.routes.draw do

  root :to => 'home#index'

  match 'auth/:provider/callback', to: 'sessions#create_omniauth'
  match 'auth/failure', to: 'home#index'
  match 'signout', to: 'sessions#destroy', as: 'signout'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :users, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :sessions
  resources :photos
  resources :tags
  resources :play, only: [:index, :create]
  resources :scores, only: [:index, :show]

end

A2/pics/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pics</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="container">
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Pics Game</a>
          <div class="nav-collapse">
            <ul class="nav">
            <li><%= link_to "Home", root_url %></li>
            <li><%= link_to "Play", play_index_url  %></li>
            <li><%= link_to "Leaderboard", scores_path %></li>
            <% if current_user %>
              <% if not current_user.admin %>
                <li><%= link_to "Past Scores", score_path(current_user.id) %></li>
              <% else %>
                <li><%= link_to "Users", users_url %></li>
                <li><%= link_to "Photos", photos_url %></li>
                <li><%= link_to "Tags", tags_url %></li>
              <% end %>
            <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
                <li><%= link_to current_user.name, edit_user_path(current_user.id) %></li>
                <% if current_user.admin %>
                  <li><%= link_to "Admin" %></li>
                <% end %>
                <li><%= link_to "Log out", log_out_path %></li>
              <% else %>
                <li><%= link_to "Sign up", sign_up_path %></li>
                <li><%= link_to "log in", log_in_path %></li>
                <li><%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div><br/>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
  <div class=container>
    <div class="row">
      <div class="span9"><%= yield %></div>
      <div class="span3"><h3>Leaderboard</h3></div>
    </div>
  </div>

</body>
</html>